name: Manage SQL Firewall Rule

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'IP a autorizar'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  update-firewall:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Add firewall rule
        run: |
          az sql server firewall-rule create \
            --resource-group database \
            --server database-server-erp \
            --name "gh-actions-${{ github.run_id }}" \
            --start-ip-address ${{ github.event.inputs.ip_address }} \